# ~/.bash_profile

[[ -s ~/.bashrc ]] && source ~/.bashrc

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# Aliases

# Use curl as a substitute for wget
alias wget="curl -O"
# Like using just 'ls', but with prettier output
alias ls='ls -GFh'
# List files only in current folder
alias ll='ls -l'
# Show numeric file permissions for current folder
alias statperms="stat -f '%A %N' *"
# Show npm links within current folder
alias findnpmlinks='find node_modules -maxdepth 2 -type l -ls'
# Show npm links in global NVM folder
alias findnpmlinksglobal='ls -ln ~/.nvm/versions/node/v8.12.0/lib/node_modules'
# Wipe out node_modules and install from scratch
alias nuke='rm -rf node_modules && npm i'
# Use pnpm to execute Nx commands
alias pnx="pnpm nx"

# Silence the MacOS warning that the default shell is zsh
export BASH_SILENCE_DEPRECATION_WARNING=1

export PATH="/usr/local/opt/python/libexec/bin:$PATH"

export PATH="/usr/local/git/bin/git-credential-github-apps:$PATH"

complete -C /opt/homebrew/bin/terraform terraform

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/alexnitta/google-cloud-sdk/path.bash.inc' ]; then . '/Users/alexnitta/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/alexnitta/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/alexnitta/google-cloud-sdk/completion.bash.inc'; fi
