export PATH="$HOME/.bin:$PATH"

eval "$(/opt/homebrew/bin/brew shellenv)"

# pnpm
export PNPM_HOME="/Users/alexnitta/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# volta
export VOLTA_HOME="/Users/alexnitta/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
# volta end
